apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app
spec:
  params:
    - name: manifest-dir
      type: string
      description: Directory containing k8s manifests
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      script: |
        kubectl apply -f $(params.manifest-dir)/deployment.yaml
        kubectl apply -f $(params.manifest-dir)/service.yaml
