apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-app-pipeline
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: "main"
    - name: image
      type: string
    - name: manifest-dir
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-push
      runAfter:
        - clone
      taskRef:
        name: build-and-push
      params:
        - name: IMAGE
          value: $(params.image)
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: deploy
      runAfter:
        - build-push
      taskRef:
        name: deploy-app
      params:
        - name: manifest-dir
          value: $(params.manifest-dir)
      workspaces:
        - name: source
          workspace: shared-workspace
