apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-tekton-pipelinerun
spec:
  pipelineRef:
    name: hello-tekton-pipeline
  params:
    - name: git-url
      value: https://github.com/sandhya/hello-tekton.git
    - name: git-revision
      value: main
    - name: image
      value: image-registry.openshift-image-registry.svc:5000/your-project/hello-tekton:latest
    - name: manifest-dir
      value: /workspace/shared-workspace/k8s
  workspaces:
    - name: shared-workspace
      emptyDir: {}
