apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-tekton-pipeline
spec:
  pipelineRef:
    name: hello-tekton-pipeline
  params:
    - name: git-url
      value: https://github.com/sandhya/hello-tekton.git
    - name: git-revision
      value: main
    - name: image
      value: docker.io/sandhyaa55/hello-app:latest
    - name: manifest-dir
      value: k8s
  workspaces:
    - name: shared-workspace
      emptyDir: {}
